// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CSjua88ShsAyHiZu40U6XvN54VY7pIc',
    appId: '1:106919015820:web:0e109c693178e0ae5ed2a9',
    messagingSenderId: '106919015820',
    projectId: 'chat-application-1381a',
    authDomain: 'chat-application-1381a.firebaseapp.com',
    storageBucket: 'chat-application-1381a.appspot.com',
    measurementId: 'G-SC5LZZVCH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPm5p8WPD46A6UKdanYao6bLZuodquSB8',
    appId: '1:106919015820:android:0c9c7a6d1a8d8edd5ed2a9',
    messagingSenderId: '106919015820',
    projectId: 'chat-application-1381a',
    storageBucket: 'chat-application-1381a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAscpM0FDYGHF8tp7vPLzPVvk-EYrRzQg',
    appId: '1:106919015820:ios:7a2312420645177b5ed2a9',
    messagingSenderId: '106919015820',
    projectId: 'chat-application-1381a',
    storageBucket: 'chat-application-1381a.appspot.com',
    iosBundleId: 'com.example.flutterBlocExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAscpM0FDYGHF8tp7vPLzPVvk-EYrRzQg',
    appId: '1:106919015820:ios:410baa417420a3cd5ed2a9',
    messagingSenderId: '106919015820',
    projectId: 'chat-application-1381a',
    storageBucket: 'chat-application-1381a.appspot.com',
    iosBundleId: 'com.example.flutterBlocExample.RunnerTests',
  );
}
